feat: добавить ветку, добавить классы, контроллеры
IvanPozhidaev/java-filmorate pull request #5
Opened 2023-03-18 06:01 UTC by IvanPozhidaev

2023-03-19 14:50 UTC, VertigoMaker requested changes
Отличная работа!

2023-03-19 14:50 UTC, VertigoMaker commented on src/main/java/ru/yandex/practicum/controller/FilmController.java
> +public class FilmController {
В целом рекомендую завести абстрактный контроллер реализующий базовый CRUD через обобщения - он позволит в будущем легко добавлять новые сущности, обеспечивая хорошее расширение приложения.

2023-03-20 03:22 UTC, IvanPozhidaev commented on src/main/java/ru/yandex/practicum/controller/FilmController.java
> +public class FilmController {
> В целом рекомендую завести абстрактный контроллер реализующий базовый CRUD через обобщения - он позволит в будущем легко добавлять новые сущности, обеспечивая хорошее расширение приложения.

Привет! Спасибо за предложение - реализовал. Также поправил .gitignore и удалил и репозитория папку .mvn.

2023-03-20 21:48 UTC, VertigoMaker approved these changes
Всё верно!

2023-03-21 03:22 UTC, merged